version: ">= 0.14.0"

formatter: markdown document

content: |-
  ## Example

  ```hcl
  {{ include "test/test.tf" }}
  ```

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    
    {{ .Content }}

    [//]: # (END_TF_DOCS)

sort:
  enabled: false
