version: ">= 0.14.0"

formatter: markdown

content: |-
  ## Example

  <details>
  <summary>
  Click to expand
  </summary>

  ```hcl
  {{ include "test/test.tf" }}
  ```

  </details>

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}

    [//]: # (END_TF_DOCS)

sort:
  enabled: false
