name: Terraform Test - wfl-instance module

env:
  terraform_directory: "terraform-modules/wfl-instance"
  terraform_version: "0.13.6"

defaults:
  run:
    working-directory: "deploy/gotc-dev/terraform"

on:
  pull_request:
    branches: 
      - master
    paths:
      - terraform-modules/wfl-instance/**
    
jobs:
  terraform_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.terraform_version }}

      # Run Terraform fmt (kind of a linter)
    - name: Terraform format check
      id: fmt
      run: terraform fmt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run Terraform init
    - name: Terraform init
      id: init
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run Terraform validate
    - name: Terraform validate
      id: validate
      run: terraform validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

